import DailyTransactionStatisticResource from '../daily-transaction-statistic/Resource'

class DailySettlementTransactionStatisticResource extends DailyTransactionStatisticResource {}

export default DailySettlementTransactionStatisticResource
